export const mocked_data = {
  column_names: [
    {
      orderId: "Order ID",
      created: "Created",
      customer: "Customer",
      fulfillment: "Fulfillment",
      total: "Total",
      profit: "Profit",
      status: "Status",
      updated: "Updated",
    },
  ],

  orders: [
    {
      orderId: 121091,
      created: "Aug 1, 2019",
      customer: "Harriet Santiago",
      customerSrc: "https://bit.ly/dan-abramov",
      fulfillment: "Unfulfilled",
      total: "$604.50",
      profit: "$182.50",
      status: "Authorized",
      updated: "Today",
    },
    {
      orderId: 121090,
      created: "Jul 21, 2019",
      customer: "Sara Graham",
      customerSrc: "https://bit.ly/tioluwani-kolawole",
      fulfillment: "Pending Receipt",
      total: "$1175.50",
      profit: "$524.50",
      status: "Paid",
      updated: "Today",
    },
    {
      orderId: 121058,
      created: "Jul 16, 2019",
      customer: "Elmer McGee",
      customerSrc: "https://bit.ly/kent-c-dodds",
      fulfillment: "Fulfilled",
      total: "$175.50",
      profit: "$78.50",
      status: "Authorized",
      updated: "Yesterday",
    },
    {
      orderId: 121999,
      created: "Jul 17, 2019",
      customer: "Victor Arnold",
      customerSrc: "https://bit.ly/ryan-florence",
      fulfillment: "Fulfilled",
      total: "$402.50",
      profit: "$83.50",
      status: "Authorized",
      updated: "Jul 26, 2019",
    },
    {
      orderId: 121049,
      created: "Jul 19, 2019",
      customer: "Harriet Scoutt",
      customerSrc: "https://bit.ly/prosper-baba",
      fulfillment: "Fulfilled",
      total: "$175.50",
      profit: "$27",
      status: "Paid",
      updated: "Jul 26, 2019",
    },
    {
      orderId: 121094,
      created: "Jul 16, 2019",
      customer: "Patrica Vaughn",
      customerSrc: "https://bit.ly/code-beast",
      fulfillment: "Pending Receipt",
      total: "$824.50",
      profit: "$113.50",
      status: "Paid",
      updated: "Jul 26, 2019",
    },
    {
      orderId: 121001,
      created: "Jul 16, 2019",
      customer: "Earl Hopkins",
      customerSrc: "https://bit.ly/sage-adebayo",
      fulfillment: "Unfulfilled",
      total: "$174.50",
      profit: "$18",
      status: "Paid",
      updated: "Jul 26, 2019",
    },
  ],

  graph_data: [
    {
      orderType: "Active Orders",
      count: 1046,
      graphColor: "#6495ed",
      graphStroke: "#0000ff",
    },
    {
      orderType: "Unfulfilled",
      count: 159,
      graphColor: "#fff68f",
      graphStroke: "#b8860b",
    },
    {
      orderType: "Pending Receipt",
      count: 154,
      graphColor: "#ffbbff",
      graphStroke: "#8a2be2",
    },
    {
      orderType: "Fulfilled",
      count: 263,
      graphColor: "#9aff9a",
      graphStroke: "#008b00",
    },
  ],
};
